#本地配置
server:
  port: 18001

##########   数据库   ##########
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username:
        password:
  #数据库
  datasource:
    url: jdbc:mysql://localhost:3306/hoxise
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  #redis配置
  data:
    redis:
      # Redis数据库索引
      database: 0
      # 连接地址
      host: localhost
      # 连接端口
      port: 6379

  # RabbitMQ 配置项，对应 RabbitProperties 配置类
  rabbitmq:
    host: 127.0.0.1 # RabbitMQ 服务的地址
    port: 5672 # RabbitMQ 服务的端口
    username: guest # RabbitMQ 服务的账号
    password: guest # RabbitMQ 服务的密码
    listener:
      simple:
        default-requeue-rejected: false  # 不重新入队失败消息

##########   其它配置   ##########
hoxise:
  #启动模式 (dev 1.登录不需要验证码;)
  runMode: dev

#短信
sms:
  aliyun:
    endpoint: dypnsapi.aliyuncs.com
    access-key: ${aliyun.sms.accessKey}
    access-secret: ${aliyun.sms.accessSecret}

