#本地配置


##########   数据库   ##########
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hoxise
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #redis配置
  data:
    redis:
      # Redis数据库索引
      database: 0
      # 连接地址
      host: localhost
      # 连接端口
      port: 6379
      # 用户名
      username:
      # 连接密码（默认为空）
      password:

  # openai
  ai:
    openai:
      # API密钥
      api-key: ${deepseek.api.key}
      # DeepSeek的API端点
      base-url: https://api.deepseek.com
      chat:
        options:
          # 可选模型：deepseek-chat(非思考模式), deepseek-reasoner (思考模式)
          model: deepseek-chat
          # 回答随机性 默认1
          temperature: 1
          # 最大返回token
          max-tokens: 5000
    #deepseek
    deepseek:
      api-key: ${deepseek.api.key}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-reasoner

    # 聊天记忆持久化
    chat:
      memory:
        repository:
          jdbc:
            # 可选值 embedded(默认,只有嵌入式数据库才建表) 、always(自动建表)、 never
            initialize-schema: always
    # 向量数据库
    vectorstore:
      # 向量模型
      embeddingModel:
        api-key: ${aliyun.bailian.ai.api.key}
        base-url: https://dashscope.aliyuncs.com/compatible-mode
        model: text-embedding-v4
      # 需要redis-stack
      redis:
        # 是否初始化索引 默认false
        initialize-schema: false
        index-name: spring-ai-index
        prefix: "embedding:"



##########   其它配置   ##########
project:
  #启动模式 (dev 1.登录不需要验证码;)
  runMode: dev
  #项目启动后是否清除Redis
  isClearCache: false
  #redis默认过期时间 Hour
  redisTimeout: 24

#文件存储
fileStorage:
  defaultType: aliyunOss
  #序列化前缀 如: 配置策略后直接访问的地址; CDN加速服务器
  serializerPrefix: ${aliyun.oss.serializerPrefix} # http://localhost:9000
  minio:
    endpoint: http://127.0.0.1:9000
    bucket: hoxise-java
    access-key: hoxise
    access-secret: hoxise-java
  aliyunOss:
    regin: cn-chengdu
    endpoint: oss-cn-chengdu.aliyuncs.com
    bucket: ${aliyun.oss.bucket}
    access-key: ${aliyun.oss.accessKey}
    access-secret: ${aliyun.oss.accessSecret}


#短信
sms:
  aliyun:
    endpoint: dypnsapi.aliyuncs.com
    accessKey: ${aliyun.sms.accessKey}
    accessSecret: ${aliyun.sms.accessSecret}

#nas云处理
nasCloud:
  #需要管理的盘符及前缀
  disk: X:\
  #需要管理的文件夹
  dirs: 动漫电影,动漫,日剧
  #启动后是否加载Embedding
  pushVectorStore: false
