server:
  port: 18888
  servlet:
    context-path: /hoxise

spring:
  profiles:
    include: local
  main:
    allow-circular-references: true

#springdoc-openapi接口文档配置
springdoc:
  swagger-ui:
    enabled: false
    path: /swagger-ui
  default-flat-param-object: true
  group-configs:
    - group: 'system'
      paths-to-match: '/**'
      packages-to-scan: cn.hoxise.system

#knife4j增强swagger文档
knife4j:
  enable: true
  setting:
    language: zh_cn

# mybatis
mybatis-plus:
  global-config:
    db-config:
      id-type: auto  # 全局主键策略
  type-handlers-package: cn.hoxise.common.base.framework.mybatis.typehandler # 类型映射

# Sa-Token (文档: https://sa-token.cc)
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒） 默认30天(2592000)，-1 代表永久有效
  timeout: 259200
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true