#本地配置

##########   数据库   ##########
spring:
  cloud:
    nacos:
      discovery:
        enabled: false # 禁用 Nacos 的注册发现
      config:
        enabled: false # 禁用 Nacos 的配置中心

  datasource:
    url: jdbc:mysql://localhost:3306/hoxise
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #redis配置
  data:
    redis:
      # Redis数据库索引
      database: 0
      # 连接地址
      host: localhost
      # 连接端口
      port: 6379
#      # 用户名
#      username:
#      # 连接密码（默认为空）
#      password:

  # RabbitMQ 配置项，对应 RabbitProperties 配置类
  rabbitmq:
    host: 127.0.0.1 # RabbitMQ 服务的地址
    port: 5672 # RabbitMQ 服务的端口
    username: guest # RabbitMQ 服务的账号
    password: guest # RabbitMQ 服务的密码
    listener:
      simple:
        retry:
          enabled: true          # 开启重试
          max-attempts: 3        # 最大重试次数
          initial-interval: 2000 # 第一次和第二次重试之间的延迟 (毫秒)
          multiplier: 2.0        # 每次重试延迟的倍数
          max-interval: 10000    # 最大重试间隔 (毫秒)

  # openai
  ai:
    openai:
      # API密钥
      api-key: ${deepseek.api.key}
      # OpenAi规范的API端点
#      base-url: https://api.deepseek.com
      chat:
        options:
          # 可选模型：deepseek-chat(非思考模式), deepseek-reasoner (思考模式)
          model: deepseek-chat
          # 回答随机性 默认1
          temperature: 1
          # 最大返回token
          max-tokens: 5000
    #deepseek
    deepseek:
      api-key: ${deepseek.api.key}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-reasoner

    # 聊天记忆持久化
    chat:
      memory:
        repository:
          jdbc:
            # 可选值 embedded(默认,只有嵌入式数据库才建表) 、always(自动建表)、 never
            initialize-schema: always
    # 向量数据库
    vectorstore:
      # 向量模型
      embeddingModel:
        api-key: ${aliyun.bailian.ai.api.key}
        base-url: https://dashscope.aliyuncs.com/compatible-mode
        model: text-embedding-v4
      # 需要redis-stack
      redis:
        # 是否初始化索引 默认false
        initialize-schema: false
        index-name: spring-ai-index
        prefix: "embedding:"



##########   其它配置   ##########

#文件存储
file-storage:
  default-type: aliyunOss
  minio:
    endpoint: http://127.0.0.1:9000
    bucket: hoxise
    access-key: hoxise
    access-secret: hoxise
    serializer-prefix: http://localhost:9000
  aliyun-oss:
    region: cn-chengdu
    endpoint: oss-cn-chengdu.aliyuncs.com
    bucket: ${aliyun.oss.bucket}
    access-key: ${aliyun.oss.accessKey}
    access-secret: ${aliyun.oss.accessSecret}
    #序列化前缀 如: 配置策略后直接访问的地址; CDN加速服务器
    serializer-prefix: ${aliyun.oss.serializerPrefix}


#短信
sms:
  aliyun:
    endpoint: dypnsapi.aliyuncs.com
    access-key: ${aliyun.sms.accessKey}
    access-secret: ${aliyun.sms.accessSecret}

#系统配置
hoxise:
  #启动模式 (dev 1.登录不需要验证码;)
  runMode: dev
  #启动后是否加载Embedding
  pushVectorStore: false