spring:
  application:
    name: hoxise-self

  profiles:
    active: local

  main:
    allow-circular-references: true #允许循环引用
    allow-bean-definition-overriding: true # 允许Bean覆盖，解决Cloud Feign问题

  servlet:
    # 文件上传相关配置项
    multipart:
      max-file-size: 16MB # 单个文件大小
      max-request-size: 32MB # 设置总上传的文件大小
  cache:
    type: redis
    redis:
      time-to-live: 1h #缓存时间


#springdoc-openapi接口文档配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
  default-flat-param-object: true
#knife4j增强swagger文档
knife4j:
  enable: true
  setting:
    language: zh_cn



