spring:
  application:
    name: hoxise-ai

  profiles:
    active: local

  main:
    allow-circular-references: true #允许循环引用
    allow-bean-definition-overriding: true # 允许Bean覆盖，解决Cloud Feign问题

  servlet:
    # 文件上传相关配置项
    multipart:
      max-file-size: 16MB # 单个文件大小
      max-request-size: 32MB # 设置总上传的文件大小
  cache:
    type: redis
    redis:
      time-to-live: 1h #缓存时间


#springdoc-openapi接口文档配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
  default-flat-param-object: true
#knife4j增强swagger文档
knife4j:
  enable: true
  setting:
    language: zh_cn

# mybatis
mybatis-plus:
  global-config:
    db-config:
      id-type: auto  # 全局默认主键策略
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    banner: false # 启动时控制台是否打印banner
  type-handlers-package: cn.hoxise.common.mybatis.core.type # 类型映射包扫描
mybatis-plus-join:
  banner: false


# Sa-Token (文档: https://sa-token.cc)
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒） 默认30天(2592000)，-1 代表永久有效
  timeout: 259200
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true


