#本地配置
server:
  port: 18004

##########   数据库   ##########
spring:
  #redis配置
  data:
    redis:
      # Redis数据库索引
      database: 8
      # 连接地址
      host: localhost
      # 连接端口
      port: 6379

  # openai
  ai:
    openai:
      # API密钥
      api-key: ${deepseek.api.key}
      # OpenAi规范的API端点
      base-url: https://api.deepseek.com
      chat:
        options:
          # 可选模型：deepseek-chat(非思考模式), deepseek-reasoner (思考模式)
          model: deepseek-reasonerw
          # 回答随机性 默认1
          temperature: 1
          # 最大返回token
          max-tokens: 5000



##########   其它配置   ##########

hoxise:
  #工作目录
  temp-dir: D:\Java\Project\env\work-dir